name: Deploy to VPS

on:
  push:
    branches:
      - main  # или другая ветка, которую ты используешь

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Подключение по SSH и перезапуск сервера
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /home/inf1nitive/fxserver/txData/QBCore_A4C195.base
            git pull origin main

            # Безопасное завершение старой screen-сессии
            if screen -list | grep -q "fivem"; then
              screen -S fivem -X quit
            fi

            # Запуск новой screen-сессии
            screen -S fivem -dm bash -c 'cd ~/fxserver && bash run.sh'