name: Deploy to VPS

on:
  push:
    branches:
      - main  # или другая ветка, которую ты используешь

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Скачиваем проект на CI
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Устанавливаем утилиту для шаблонов
      - name: Install envsubst
        run: sudo apt-get update && sudo apt-get install -y gettext-base

      # 3. Генерируем server.cfg из server.template.cfg
      - name: Generate server.cfg from template
        env:
          CFX_LICENSE_KEY: ${{ secrets.CFX_LICENSE_KEY }}
          RCON_PASSWORD:   ${{ secrets.RCON_PASSWORD }}
          STEAM_API_KEY:   ${{ secrets.STEAM_API_KEY }}
          DB_URL:          ${{ secrets.DB_URL }}
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          GAME_PORT:       ${{ secrets.GAME_PORT }}
        run: |
          envsubst < server.template.cfg > server.cfg

      # 4. Передаём server.cfg на VPS
      - name: Upload server.cfg to VPS
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: server.cfg
          target: /home/inf1nitive/fxserver/txData/QBCore_A4C195.base

      # 5. Подключаемся по SSH и перезапускаем сервер
      - name: Restart FiveM via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /home/inf1nitive/fxserver/txData/QBCore_A4C195.base
            git pull origin main

            if screen -list | grep -q "fivem"; then
              screen -S fivem -X quit
              sleep 5
            fi

            screen -S fivem -dm bash -c 'cd ~/fxserver && bash run.sh'
